### ISSUE TITLE
Compiled binary files from release detected as Trojan.

### ISSUE THREAD

**Issue by MTW-Development** [erucix/Huggingface-API#1]
VirusTotal detected the .exe file as a trojan as seen in the image below.

![image](https://github.com/erucix/Huggingface-API/assets/87285710/43001a8d-5238-4c09-bc0d-1fdabc67da77)

Here is the complete VirusTotal log:  https://www.virustotal.com/gui/file/ac959daa83029d3c9dc10c5721d6f5d766587c3fbe7885125a499b3c705aa0af/detection

**Comment by erucix** [comment]
This is false positive tho. You can manually compile it using `pkg` yourself and get the same result in virustotal.
